import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/global.scss";
import TopBar from "@/components/Home/TopBar/TopBar";
import Footer from "@/components/Footer/Footer";
import { QueryProvider } from "@/providers/QueryProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex h-screen flex-col overflow-hidden`}
      >
        <QueryProvider>
          <div className="main-scroll flex-1 flex flex-col min-h-0 overflow-y-auto overflow-x-hidden">
            <TopBar />
            <main className="flex-1 flex flex-col min-h-0">
              <div className="flex flex-col w-full flex-1">
                {children}
              </div>
              <Footer />
            </main>
          </div>
        </QueryProvider>
      </body>
    </html>
  );
}
